name: Build APK Manual
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --user --upgrade buildozer "cython<3.0.0" virtualenv

      - name: Install Android SDK Platform 31
        run: |
          # এখানে সরাসরি পাথ ব্যবহার করা হয়েছে যাতে 'command not found' না আসে
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platforms;android-31" "build-tools;31.0.0" "platform-tools"

      - name: Cache Buildozer Directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-${{ runner.os }}-

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          buildozer android debug
        continue-on-error: false

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: YI-Bank-Final-APK
          path: bin/*.apk
          
